### ISSUE TITLE
Update actions/github-script dependency

### ISSUE THREAD

**Issue by jeremycopinlm** [ChristopherHX/conditional#4]
Hello it's me again

About Github Actions warning :

Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/github-script@v6, actions/upload-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

Could you update your action please ? Thanks again

**Comment by ChristopherHX** [comment]
Hi,

May I ask what is your reason to keep using this action? Could be one of
- Never change a running system
- Want to use expression in `uses`?

The original usecase of this action, e.g. emulate `if` in composite actions isn't needed anymore. Due to GitHub has implemented native support for regular if statements ca. 2 years ago.

**Comment by ChristopherHX** [comment]
I have just configured dependabot, that it should open PR's on dependency updates. We will see if it creates a PR for `v8` of the dependency in far future or it does nothing for whatever reason

**Comment by jeremycopinlm** [comment]
Hello
Thank you
I continue to use it in the middle of a huge mutualized workflow, if some user want to add a specific composite action at that point of the main workflow execution (additional steps I can't manage for all my users and depending of their context).
